// mygf/src/components/pages/tracks/data.ts
import type { Course } from "./types";

export const COURSES: Course[] = [
  {
    id: "1",
    title: "Backend APIs with Django",
    track: "Programming",
    level: "Beginner",
    durationHours: 12,
    rating: 4.7,
    ratingCount: 180,
    cover: "https://picsum.photos/seed/django/400/200",
    pill: "Preview",
  },
  {
    id: "2",
    title: "Advanced UI Systems in Figma",
    track: "Design",
    level: "Advanced",
    durationHours: 8,
    rating: 4.5,
    ratingCount: 230,
    cover: "https://picsum.photos/seed/figma/400/200",
    pill: "Top Rated",
  },
  {
    id: "3",
    title: "Data Visualization with D3",
    track: "Data",
    level: "Intermediate",
    durationHours: 10,
    rating: 4.8,
    ratingCount: 310,
    cover: "https://picsum.photos/seed/d3/400/200",
  },
  {
    id: "4",
    title: "Microservices with Node.js",
    track: "Programming",
    level: "Advanced",
    durationHours: 14,
    rating: 4.3,
    ratingCount: 205,
    cover: "https://picsum.photos/seed/node/400/200",
    pill: "Preview",
  },
  {
    id: "5",
    title: "Product Design Foundations",
    track: "Design",
    level: "Beginner",
    durationHours: 9,
    rating: 4.6,
    ratingCount: 162,
    cover: "https://picsum.photos/seed/design/400/200",
  },
  {
    id: "6",
    title: "Creative Coding with p5.js",
    track: "Programming",
    level: "Beginner",
    durationHours: 6,
    rating: 4.9,
    ratingCount: 295,
    cover: "https://picsum.photos/seed/p5/400/200",
  },
];
